backend/core/urls.py
from django.urls import path
from backend.core import views as v


app_name = 'core'


urlpatterns = [
    path('', v.index, name='index'),
    path('send-email/', v.send_email_simple_view, name='send_email_simple_view'),
    path('send-email/html/', v.send_email_html_view, name='send_email_html_view'),
    path(
        'send-email/html-template/',
        v.send_email_html_template_view,
        name='send_email_html_template_view'
    ),
    path(
        'send-email/licenses/',
        v.send_email_with_licenses,
        name='send_email_with_licenses'
    ),
]

backend/urls.py
from django.urls import include, path
from django.contrib import admin
urlpatterns = [
    path('', include('backend.core.urls', namespace='core')),
    path('admin/', admin.site.urls),
]

backend/core/models.py
from django.db import models


class TimeStampedModel(models.Model):
    created = models.DateTimeField(
        'criado em',
        auto_now_add=True,
        auto_now=False
    )
    modified = models.DateTimeField(
        'modificado em',
        auto_now_add=False,
        auto_now=True
    )

    class Meta:
        abstract = True

backend/crm/models.py
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    name = models.CharField('nome', max_length=100, unique=True)
    email = models.EmailField()

    class Meta:
        ordering = ('name',)
        verbose_name = 'cliente'
        verbose_name_plural = 'clientes'

    def __str__(self):
        return self.name


class Seller(User):

    class Meta:
        ordering = ('first_name',)
        verbose_name = 'vendedor'
        verbose_name_plural = 'vendedores'

    def __str__(self):
        return self.get_full_name()


class TypeLicense(models.Model):
    name = models.CharField('nome', max_length=50)

    class Meta:
        ordering = ('name',)
        verbose_name = 'tipo'
        verbose_name_plural = 'tipos'

    def __str__(self):
        return self.name


class License(models.Model):
    name = models.CharField('nome', max_length=100)
    type_license = models.ForeignKey(
        TypeLicense,
        verbose_name='tipo',
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    expiration_date = models.DateTimeField('data de validade')
    customer = models.ForeignKey(
        Customer,
        verbose_name='cliente',
        related_name='customers',
        on_delete=models.CASCADE,
    )
    seller = models.ForeignKey(
        Seller,
        verbose_name='vendedor',
        related_name='sellers',
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = ('name',)
        verbose_name = 'licença'
        verbose_name_plural = 'licenças'

    def __str__(self):
        return self.name

backend/core/views.py
from datetime import datetime
from decouple import config

from backend.crm.models import Customer, License
from django.http import HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string

from .core_send_email import send_email_simple, send_email_html


def index(request):
    template_name = 'index.html'
    total_customers = Customer.objects.all().count()
    total_licenses = License.objects.all().count()
    context = {
        'total_customers': total_customers,
        'total_licenses': total_licenses,
    }
    return render(request, template_name, context)


def send_email_simple_view(request):
    data = datetime.now().isoformat(' ')
    subject = f'Test {data}'
    body = f'Hello World {data}'
    sender = config('SENDER')
    receiver = [config('SENDER'), ]
    send_email_simple(subject, body, sender, receiver)
    return HttpResponse('E-mail enviado com sucesso.')


def send_email_html_view(request):
    data = datetime.now().isoformat(' ')
    subject = f'HTML e-mail {data}'
    html_content = f'<h1>Olá, tudo bem?</h1><p>Mensagem <strong>importante</strong> <i>{data}</i></p>'
    sender = 'admpgsa.regis@gmail.com'
    receiver = ['admpgsa.regis@gmail.com']
    send_email_html(subject=subject, body=html_content, sender=sender, receiver=receiver)
    return HttpResponse('E-mail enviado com sucesso.')


def send_email_html_template_view(request):
    data = datetime.now().isoformat(' ')
    subject = f'HTML e-mail com template {data}'
    context = {'name': 'Regis'}
    html_content = render_to_string('emails/email_hello.html', context)
    sender = 'admpgsa.regis@gmail.com'
    receiver = ['admpgsa.regis@gmail.com']
    send_email_html(subject=subject, body=html_content, sender=sender, receiver=receiver)
    return HttpResponse('E-mail enviado com sucesso.')


def send_email_with_licenses(request):
    customer = Customer.objects.first()
    licenses = License.objects.filter(customer=customer)
    seller = licenses[0].seller

    subject = f'As licenças de {customer.name} vão expirar em breve'
    context = {
        'seller_name': seller.get_full_name(),
        'customer_name': customer.name,
        'customer_email': customer.email,
        'quantity_licenses': licenses.count(),
        'licenses': licenses,
    }
    html_content = render_to_string('emails/email_licenses.html', context)
    sender = 'admpgsa.regis@gmail.com'
    # receiver = [seller.email, 'admpgsa.regis@gmail.com']
    receiver = ['admpgsa.regis@gmail.com']
    send_email_html(subject=subject, body=html_content, sender=sender, receiver=receiver)
    return HttpResponse('E-mail enviado com sucesso.')

backend/crm/views.py
from django.shortcuts import render

# Create your views here.

backend/core/templates/_form.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <strong>Company</strong>
        <small>Form</small>
      </div>
      <div class="card-body">
        <div class="form-group">
          <label for="company">Company</label>
          <input class="form-control" id="company" type="text" placeholder="Enter your company name">
        </div>
        <div class="form-group">
          <label for="street">Street</label>
          <input class="form-control" id="street" type="text" placeholder="Enter street name">
        </div>
        <div class="row">
          <div class="form-group col-sm-4">
            <label for="postal-code">City</label>
            <input class="form-control" id="city" type="text" placeholder="Enter your city">
          </div>
          <div class="form-group col-sm-4">
            <label for="state">State</label>
            <select class="form-control use-select2" id="state" name="state">
              <option value="">Please select</option>
              <option value="AC">Acre</option>
              <option value="AL">Alagoas</option>
              <option value="AP">Amapá</option>
              <option value="AM">Amazonas</option>
              <option value="BA">Bahia</option>
              <option value="CE">Ceará</option>
              <option value="DF">Distrito Federal</option>
              <option value="ES">Espírito Santo</option>
              <option value="GO">Goiás</option>
              <option value="MA">Maranhão</option>
              <option value="MT">Mato Grosso</option>
              <option value="MS">Mato Grosso do Sul</option>
              <option value="MG">Minas Gerais</option>
              <option value="PA">Pará</option>
              <option value="PB">Paraíba</option>
              <option value="PR">Paraná</option>
              <option value="PE">Pernambuco</option>
              <option value="PI">Piauí</option>
              <option value="RJ">Rio de Janeiro</option>
              <option value="RN">Rio Grande do Norte</option>
              <option value="RS">Rio Grande do Sul</option>
              <option value="RO">Rondônia</option>
              <option value="RR">Roraima</option>
              <option value="SC">Santa Catarina</option>
              <option value="SP">São Paulo</option>
              <option value="SE">Sergipe</option>
              <option value="TO">Tocantins</option>
            </select>
          </div>
          <div class="form-group col-sm-4">
            <label for="postal-code">Postal Code</label>
            <input class="form-control" id="postal-code" type="text" placeholder="Postal Code">
          </div>
        </div> <!-- row -->
        <div class="form-group">
          <label for="country">Country</label>
          <input class="form-control" id="country" type="text" placeholder="Country name">
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <textarea class="form-control" id="description" type="text" rows="5"></textarea>
        </div>
        <div class="float-right">
          <button class="btn btn-primary" type="submit">Save</button>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

{% block js %}
  <script>
    $(document).ready(function() {
      $('.use-select2').select2();
    });
  </script>
{% endblock js %}

backend/core/templates/_form_widget_tweaks.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block content %}
<div class="col-lg-12">
  <div class="card">
    <div class="card-header">
      <strong>Company</strong>
      <small>Form</small>
    </div>
    <div class="card-body">
      <form method="POST">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group{% if field.errors %} has-error {% endif %}">
          <label for="{{ field.id_for_label }}">
            {% if field.field.required %}
            <span class="required">{{ field.label }}</span>
            {% else %}
            {{ field.label }}
            {% endif %}
          </label>
          {% render_field field class="form-control" %}
          {% for error in field.errors %}
          <span class="text-muted">{{ error }}</span>
          {% endfor %}
        </div>
        {% endfor %}
        <div class="float-right">
          <button class="btn btn-primary" type="submit">Salvar</button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

{% block js %}
  <script>
    $(document).ready(function() {
      $('.use-select2').select2();
    });
  </script>
{% endblock js %}

backend/core/templates/_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        Title
        <span class="float-right">1 of 10 results (100 total)</span>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-md-auto">
            <a class="btn btn-primary" href="{% url 'core:create' %}">
              <i class="fa fa-plus"></i>
              Add
            </a>
          </div>
          <div class="col">
            <form action="." method="GET">
              <div class="row">
                <div class="col p-ari-5">
                  <input name="search" class="form-control mb-2" type="text" placeholder="Search..." />
                </div>
                <div class="col-auto">
                  <button class="btn btn-success mb-2" type="submit">OK</button>
                  <button class="btn btn-link mb-2">Clear</button>
                </div>
              </div>
            </form>
          </div>
        </div>
        <!-- TABLE -->
        <table class="table table-responsive-sm table-hover table-striped">
          <thead>
            <tr>
              <th>Username</th>
              <th>Date registered</th>
              <th>Role</th>
              <th class="text-center">Status</th>
              <th class="text-center">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                <a href="{% url 'core:detail' %}">Chetan Mohamed</a>
              </td>
              <td>2020/01/01</td>
              <td>Member</td>
              <td class="text-center">
                <span class="badge badge-success">Active</span>
              </td>
              <td class="text-center">
                <a href="">
                  <i class="fa fa-edit"></i>
                </a>
              </td>
            </tr>
            <tr>
              <td>
                <a href="{% url 'core:detail' %}">Derick Maximinus</a>
              </td>
              <td>2020/02/01</td>
              <td>Staff</td>
              <td class="text-center">
                <span class="badge badge-danger">Banned</span>
              </td>
              <td class="text-center">
                <a href="">
                  <i class="fa fa-edit"></i>
                </a>
              </td>
            </tr>
            <tr>
              <td>
                <a href="{% url 'core:detail' %}">Estavan Lykos</a>
              </td>
              <td>2020/02/01</td>
              <td>Admin</td>
              <td class="text-center">
                <span class="badge badge-secondary">Inactive</span>
              </td>
              <td class="text-center">
                <a href="">
                  <i class="fa fa-edit"></i>
                </a>
              </td>
            </tr>
            <tr>
              <td>
                <a href="{% url 'core:detail' %}">Friderik Dávid</a>
              </td>
              <td>2020/03/01</td>
              <td>Member</td>
              <td class="text-center">
                <span class="badge badge-warning">Pending</span>
              </td>
              <td class="text-center">
                <a href="">
                  <i class="fa fa-edit"></i>
                </a>
              </td>
            </tr>
            <tr>
              <td>
                <a href="{% url 'core:detail' %}">Samppa Nori</a>
              </td>
              <td>2020/01/21</td>
              <td>Staff</td>
              <td class="text-center">
                <span class="badge badge-success">Active</span>
              </td>
              <td class="text-center">
                <a href="">
                  <i class="fa fa-edit"></i>
                </a>
              </td>
            </tr>
          </tbody>
        </table>
        <!-- pagination -->
        {% include "includes/pagination.html" %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

backend/core/templates/includes/breadcrumb.html
<!-- Breadcrumb-->
<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="{% url 'core:index' %}">Home</a>
  </li>
  <li class="breadcrumb-item">
    <a href=".">List</a>
  </li>
  <li class="breadcrumb-item active">Dashboard</li>
  <!-- Breadcrumb Menu-->
  <!-- <li class="breadcrumb-menu d-md-down-none">
    <div class="btn-group" role="group" aria-label="Button group">
      <a class="btn" href="">
        <i class="icon-speech"></i>
      </a>
      <a class="btn" href="{% url 'core:index' %}">
        <i class="icon-graph"></i>  Dashboard</a>
      <a class="btn" href="">
        <i class="icon-settings"></i>  Settings</a>
    </div>
  </li> -->
  {% block breadcrumb %}{% endblock breadcrumb %}
</ol>

backend/core/templates/includes/navbar.html
{% load static %}
<header class="app-header navbar">
  <button class="navbar-toggler sidebar-toggler d-lg-none mr-auto" type="button" data-toggle="sidebar-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'core:index' %}">
    <img class="navbar-brand-full" src="{% static 'img/brand/logo.svg' %}" width="89" height="25" alt="CoreUI Logo">
    <img class="navbar-brand-minimized" src="{% static 'img/brand/sygnet.svg' %}" width="30" height="30" alt="CoreUI Logo">
  </a>
  <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button" data-toggle="sidebar-lg-show">
    <span class="navbar-toggler-icon"></span>
  </button>
  <ul class="nav navbar-nav d-md-down-none">
    <li class="nav-item px-3">
      <a class="nav-link" href="{% url 'core:index' %}">Dashboard</a>
    </li>
    <li class="nav-item px-3">
      <a class="nav-link" href="/admin/crm/seller/">Vendedores</a>
    </li>
    <li class="nav-item px-3">
      <a class="nav-link" href="/admin/crm/customer/">Clientes</a>
    </li>
    <li class="nav-item px-3">
      <a class="nav-link" href="/admin/crm/license/">Licenças</a>
    </li>
  </ul>
  <ul class="nav navbar-nav ml-auto">
    <!-- <li class="nav-item dropdown d-md-down-none">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="icon-bell"></i>
        <span class="badge badge-pill badge-danger">5</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg">
        <div class="dropdown-header text-center">
          <strong>You have 5 notifications</strong>
        </div>
        <a class="dropdown-item" href="#">
          <i class="icon-user-follow text-success"></i> New user registered</a>
        <a class="dropdown-item" href="#">
          <i class="icon-user-unfollow text-danger"></i> User deleted</a>
        <a class="dropdown-item" href="#">
          <i class="icon-chart text-info"></i> Sales report is ready</a>
        <a class="dropdown-item" href="#">
          <i class="icon-basket-loaded text-primary"></i> New client</a>
        <a class="dropdown-item" href="#">
          <i class="icon-speedometer text-warning"></i> Server overloaded</a>
        <div class="dropdown-header text-center">
          <strong>Server</strong>
        </div>
        <a class="dropdown-item" href="#">
          <div class="text-uppercase mb-1">
            <small>
              <b>CPU Usage</b>
            </small>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-info" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
          <small class="text-muted">348 Processes. 1/4 Cores.</small>
        </a>
        <a class="dropdown-item" href="#">
          <div class="text-uppercase mb-1">
            <small>
              <b>Memory Usage</b>
            </small>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-warning" role="progressbar" style="width: 70%" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
          <small class="text-muted">11444GB/16384MB</small>
        </a>
        <a class="dropdown-item" href="#">
          <div class="text-uppercase mb-1">
            <small>
              <b>SSD 1 Usage</b>
            </small>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-danger" role="progressbar" style="width: 95%" aria-valuenow="95" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
          <small class="text-muted">243GB/256GB</small>
        </a>
      </div>
    </li>
    <li class="nav-item dropdown d-md-down-none">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="icon-list"></i>
        <span class="badge badge-pill badge-warning">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg">
        <div class="dropdown-header text-center">
          <strong>You have 5 pending tasks</strong>
        </div>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">Upgrade NPM &amp; Bower
            <span class="float-right">
              <strong>0%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-info" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">ReactJS Version
            <span class="float-right">
              <strong>25%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-danger" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">VueJS Version
            <span class="float-right">
              <strong>50%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-warning" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">Add new layouts
            <span class="float-right">
              <strong>75%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-info" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item" href="#">
          <div class="small mb-1">Angular 2 Cli Version
            <span class="float-right">
              <strong>100%</strong>
            </span>
          </div>
          <span class="progress progress-xs">
            <div class="progress-bar bg-success" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
          </span>
        </a>
        <a class="dropdown-item text-center" href="#">
          <strong>View all tasks</strong>
        </a>
      </div>
    </li>
    <li class="nav-item dropdown d-md-down-none">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="icon-envelope-letter"></i>
        <span class="badge badge-pill badge-info">7</span>
      </a>
      <div class="dropdown-menu dropdown-menu-right dropdown-menu-lg">
        <div class="dropdown-header text-center">
          <strong>You have 4 messages</strong>
        </div>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/7.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-success"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">Just now</small>
            </div>
            <div class="text-truncate font-weight-bold">
              <span class="fa fa-exclamation text-danger"></span> Important message</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/6.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-warning"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">5 minutes ago</small>
            </div>
            <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/5.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-danger"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">1:52 PM</small>
            </div>
            <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item" href="#">
          <div class="message">
            <div class="py-3 mr-3 float-left">
              <div class="avatar">
                <img class="img-avatar" src="{% static 'img/avatars/4.jpg' %}" alt="admin@bootstrapmaster.com">
                <span class="avatar-status badge-info"></span>
              </div>
            </div>
            <div>
              <small class="text-muted">John Doe</small>
              <small class="text-muted float-right mt-1">4:03 PM</small>
            </div>
            <div class="text-truncate font-weight-bold">Lorem ipsum dolor sit amet</div>
            <div class="small text-muted text-truncate">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt...</div>
          </div>
        </a>
        <a class="dropdown-item text-center" href="#">
          <strong>View all messages</strong>
        </a>
      </div>
    </li>
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <img class="img-avatar" src="{% static 'img/avatars/6.jpg' %}" alt="avatar">
      </a>
      <div class="dropdown-menu dropdown-menu-right">
        <div class="dropdown-header text-center">
          <strong>Account</strong>
        </div>
        <a class="dropdown-item" href="#">
          <i class="fa fa-bell-o"></i> Updates
          <span class="badge badge-info">42</span>
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-envelope-o"></i> Messages
          <span class="badge badge-success">42</span>
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-tasks"></i> Tasks
          <span class="badge badge-danger">42</span>
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-comments"></i> Comments
          <span class="badge badge-warning">42</span>
        </a>
        <div class="dropdown-header text-center">
          <strong>Settings</strong>
        </div>
        <a class="dropdown-item" href="#">
          <i class="fa fa-user"></i> Profile</a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-wrench"></i> Settings</a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-usd"></i> Payments
          <span class="badge badge-secondary">42</span>
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-file"></i> Projects
          <span class="badge badge-primary">42</span>
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">
          <i class="fa fa-shield"></i> Lock Account</a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-lock"></i> Logout</a>
      </div>
    </li> -->
  </ul>
  <!-- <button class="navbar-toggler aside-menu-toggler d-md-down-none" type="button" data-toggle="aside-menu-lg-show">
    <span class="navbar-toggler-icon"></span>
  </button> -->
  <!-- <button class="navbar-toggler aside-menu-toggler d-lg-none" type="button" data-toggle="aside-menu-show">
    <span class="navbar-toggler-icon"></span>
  </button> -->
</header>

backend/core/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="row mb-2">
  <div class="col-sm-2">
    <a class="btn btn-primary" href="{% url 'core:send_email_simple_view' %}">Enviar e-mail</a>
  </div>
  <div class="col-sm-4">
    <a class="btn btn-info" href="{% url 'core:send_email_html_view' %}">Enviar e-mail em HTML</a>
  </div>
  <div class="col-sm-3">
    <a class="btn btn-success" href="{% url 'core:send_email_html_template_view' %}">Enviar e-mail em HTML com template</a>
  </div>
  <div class="col-sm-3">
    <a class="btn btn-success" href="{% url 'core:send_email_with_licenses' %}">Enviar e-mail com as licenças</a>
  </div>
</div>

<!-- Members -->
{% include "dashboard/members.html" %}
<!-- Graphic -->
{% include "dashboard/traffic.html" %}
{% endblock content %}